
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01ETXlOekV5TURJeE4xb1hEVE13TURNeU5URXlNREl4TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHpyCnNQbWI4ZFYxT0NsWEt6MHJqaVVqN0lhV2N4ZEp3R1RGUHEwM0VpT01LYjhKcnBPSllqQjI4aVdKRkhWTVlJSGsKSzhIdGg0MlAzQThqVHUzcVN3WUJJenBFcGk3R01TRUlmT0t0RnNqd0hxTWhmZzRjNFRsK0Q0MDVEaU1lKzVPeQpqa2haWnBnUUw2c29YaVVRYmYydnpobm9vYWRFbUFoaTZpSzlKY1J5cTh3RGNmMlpKc2U3MzJVS2dBNnRPazBpCnlWbWVyU2VMODVUQ2NjTjJiSmV0REJza055ZkV3Q09MWWlrTERrK1B3MW42ZGUzTXFNVU1rblJaSC8rb1Y0dHAKTmFnczYxdDk0VUU1Nm5zcFl4OWt3RmpDcGQ4WGorV2REcmh0TVNneWFzV2tMN0dUUllUL0l4NDcrYVgvUE1LWQpCajVsaVJLWHNiNzUyQ0RTUjdFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFRk5uMEJYVmxsTVkvcTY0Q3gwK2Q0ZFpaNWYKVEsrSEc2b0kyNzF4c2NGTnFzR25wU1FNSEZjYzVZRUtuNmdiSUF5VXVGWjhhbU4zeGszalJGVHNocG8rbHhkTgpiN21BV09iQTZkVThZWnBnU0d1QXFnQnJ0VDlOdzJJY1BkN09VdVkvVFRGQ1RFYjVqekFoeERCazM5NGt5V0E4CitMQ3QrdnBtSExBZWVZWTk3U3F3ZDlWTlpxR3VrZzZSOFRYQ3duV056QUViWEx3dkl1TTRUZVgySy9ISjFsbkkKTkVEZ3pSN1BQcHFTY3FRVENPTURMS21OdWRaZ1lnWjAxdVNKakVEYUo0aUszREZ1RVJEL0ZNeFhyM0hSQWdLMgo4MUFXbWxwdGJFcHpVeHlBWTFDYTZZMDNZNGVqbC9IamdkSUwwbGtRd1Z0aldtWHhueXNaMXFPQjlMaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://d692ac6a-531d-43b0-b1f0-5b8bb444bbc7.cpc2-us-central.linodelke.net:443
  name: kubernetes

users:
- name: lke-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkFsZDhYZ09zMS1JUWZBbzdmcENUOWdZcHpPZjVQRTdPaXVYUlZzaHZ2UDQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tbnZ2NDQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZGY1MWMzMWQtYjcyOC00OWVmLTg2NzktM2Q5MGFkZWFjNjIxIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.gI4U57trr_Y3ZLONB2xjlYP6dMRLeLjm39QdORNAbtgiZbbSBmw7lq2N2fCCpBHcMQQOl7DeqbshYJnG-nBdRv1LeBhAXqOz6mZrB6jDGFal0sNMm47H4EjnbufKXfPXr79-KgngSundrIOKub56x21Hsn04aAP6uepTBid75IuLLyYYW6UchSKIGgnVfxIQr-2byCviLHpa0mG6qJvbK8ruIlmCseJep51rOVNvFJqTdmWPzreewzt9b4qZ8BUNvv-fQnf1lchAD7O_30iLJZrQDy5JRdvc0kshZWNgpqvvAWHMUduewVR3_nVRT5UBog72RZwQizMzEMj0XgLMpg

contexts:
- context:
    cluster: kubernetes
    namespace: default
    user: lke-admin
  name: lke-admin-ctx

current-context: lke-admin-ctx
