version: "3"


services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGODB_ROOT_USER=username
      - MONGODB_ROOT_PASSWORD=password
    volumes:
      - ./mongo:/data/db
    networks:
      - docker-net
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - "mongo"
    networks:
      - docker-net

networks:
  docker-net:

