version: "3"


services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db  
    networks:
      - docker-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - "mongo"
    networks:
      - docker-net


networks:
  docker-net:
